### ISSUE TITLE
Right clicking with the toolbox throws an exception

### ISSUE THREAD

**Issue by PAndaContron** [Terasology/StructureTemplates#21] opened 2017-12-03 19:13 UTC
I ran the module with all of its dependencies loaded, not sure what exactly is going wrong here. Every time I right click with the toolbox, instead of bringing up the dialog like it's supposed to, it throws and catches an exception which is printed to the console. Here is the stack trace:

`14:08:34.253 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.internal.NUIManagerInternal.createScreen(NUIManagerInternal.java:282)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.createScreen(NUIManagerInternal.java:258)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:309)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:304)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:1)
	at org.terasology.logic.characters.interactions.InteractionSystem.onInteractionStartPredicted(InteractionSystem.java:118)
	at org.terasology.logic.characters.interactions.InteractionSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.characters.interactions.InteractionSystem.onActivationPredicted(InteractionSystem.java:78)
	at org.terasology.logic.characters.interactions.InteractionSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:289)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:268)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:205)
	at org.terasology.logic.players.LocalPlayer.activateOwnedEntityAsClient(LocalPlayer.java:174)
	at org.terasology.logic.players.LocalPlayerSystem.onUseItemButton(LocalPlayerSystem.java:537)
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:289)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:268)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.input.internal.BindableButtonImpl.update(BindableButtonImpl.java:210)
	at org.terasology.input.InputSystem.processBindRepeats(InputSystem.java:302)
	at org.terasology.input.InputSystem.update(InputSystem.java:126)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:196)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:400)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:376)
	at org.terasology.engine.Terasology.main(Terasology.java:154)`

**Comment by meetcshah19** [comment] 2020-04-11 08:38
Cannot reproduce. Most probably an obsolete issue.

**Comment by skaldarnar** [comment] 2020-04-11 14:41
I also used the toolbox extensively in the last days - closing as fixed 👍

**Closed by skaldarnar** 2020-04-11 14:41 UTC
